### ISSUE TITLE
Resolve CircleCI vs Travis

### ISSUE THREAD

**Issue by eblur** [astropy/astropy-tutorials#272]
I am now getting emails from Travis saying that the master branch does not pass tests. However, they do pass on CircleCI.  We need to resolve this.

See also Issue #268 

The error I'm getting on the latest Travis run:
```
INFO: Processing notebook quantities.ipynb (in /home/travis/build/astropy/astropy-tutorials/tutorials/notebooks/quantities) [__main__]
DEBUG: Executing notebook using kwargs "{'timeout': 900, 'kernel_name': 'python3'}"... [__main__]
Traceback (most recent call last):
  File "scripts/convert.py", line 305, in <module>
    overwrite=args.overwrite, kernel_name=args.kernel_name)
  File "scripts/convert.py", line 218, in process_notebooks
    nbc.execute()
  File "scripts/convert.py", line 95, in execute
    executor.preprocess(nb, {'metadata': {'path': self.path_only}})
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 361, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 385, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
A13 = 7.4e-8 / u.s
A18 = 8.8e-8 / u.s
C = 3e14 * (nu18/nu13)**3 * (A13/A18) / (u.K * u.cm**2 * u.km *(1/u.s))
C
------------------
NameErrorTraceback (most recent call last)
<ipython-input-26-a1dd694d01d6> in <module>
      2 A18 = 8.8e-8 / u.s
      3 
----> 4 C = 3e14 * (nu18/nu13)**3 * (A13/A18) / (u.K * u.cm**2 * u.km *(1/u.s))
      5 C
NameError: name 'nu18' is not defined
NameError: name 'nu18' is not defined
```

**Comment by kakirastern** [comment]
Same issue experienced as on Feb. 12th, 2019 while trying to pass Travis.

**Comment by kakirastern** [comment]
It has to do with the "Quantities tutorial" I am working on adding a keyword to in PR #329. Let me see what is wrong with that file...

**Comment by kakirastern** [comment]
Think bug has been fixed for now unless old PR's are merged without rebasing prior to PR #329... Cf. Commit [https://github.com/astropy/astropy-tutorials/commit/d3789d7d3ce2c0b95df2a91128d8edb2bc68d97b](https://github.com/astropy/astropy-tutorials/commit/d3789d7d3ce2c0b95df2a91128d8edb2bc68d97b), as of February 19th, 2019. Would advise rebasing all old PR's before merging in the near future.

**Comment by kelle** [comment]
close?

**Comment by kakirastern** [comment]
I will need to work on some tutorial notebooks further so that some "bugs" won't periodically crop up in Travis/Circle CI. But the above issue has definitely been fixed. So now this can be safely closed.

**Comment by adrn** [comment]
See #349
