### ISSUE TITLE
Experiencing difficulties building html docs locally

### ISSUE THREAD

**Issue by kakirastern** [astropy/astropy-tutorials#356]
If I try to build the html docs locally, I would get the error traceback below:
```
sphinx-build -b html -d build/doctrees   tutorials build/html
Running Sphinx v1.8.4
INFO: Processing notebook conesearch.ipynb (in /Users/koychui/astropy-tutorials/tutorials/notebooks/vo) [convert]

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/anaconda3/envs/astropy-dev/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/anaconda3/envs/astropy-dev/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/Users/koychui/astropy-tutorials/tutorials/conf.py", line 164, in <module>
    process_notebooks(nb_tutorials_path, **processkwargs)
  File "/Users/koychui/astropy-tutorials/scripts/convert.py", line 226, in process_notebooks
    nbc.execute()
  File "/Users/koychui/astropy-tutorials/scripts/convert.py", line 95, in execute
    executor.preprocess(nb, {'metadata': {'path': self.path_only}})
  File "/anaconda3/envs/astropy-dev/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 354, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/anaconda3/envs/astropy-dev/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/anaconda3/envs/astropy-dev/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 378, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
c = coord.SkyCoord.from_name('M31', frame='icrs')
print(c)
------------------

---------------------------------------------------------------------------
NameResolveError                          Traceback (most recent call last)
<ipython-input-3-d613bbe5dbea> in <module>
----> 1 c = coord.SkyCoord.from_name('M31', frame='icrs')
      2 print(c)

/anaconda3/envs/astropy-dev/lib/python3.7/site-packages/astropy/coordinates/sky_coordinate.py in from_name(cls, name, frame, parse)
   1691         from .name_resolve import get_icrs_coordinates
   1692 
-> 1693         icrs_coord = get_icrs_coordinates(name, parse)
   1694         icrs_sky_coord = cls(icrs_coord)
   1695         if frame in ('icrs', icrs_coord.__class__):

/anaconda3/envs/astropy-dev/lib/python3.7/site-packages/astropy/coordinates/name_resolve.py in get_icrs_coordinates(name, parse)
    178         raise NameResolveError("All Sesame queries failed. Unable to "
    179                                "retrieve coordinates. See errors per URL "
--> 180                                "below: \n {}".format("\n".join(messages)))
    181 
    182     ra, dec = _parse_response(resp_data)

NameResolveError: All Sesame queries failed. Unable to retrieve coordinates. See errors per URL below: 
 http://cdsweb.u-strasbg.fr/cgi-bin/nph-sesame/A?M31: timed out
http://vizier.cfa.harvard.edu/viz-bin/nph-sesame/A?M31: Request took longer than the allowed 10.0 seconds
NameResolveError: All Sesame queries failed. Unable to retrieve coordinates. See errors per URL below: 
 http://cdsweb.u-strasbg.fr/cgi-bin/nph-sesame/A?M31: timed out
http://vizier.cfa.harvard.edu/viz-bin/nph-sesame/A?M31: Request took longer than the allowed 10.0 seconds


gmake: *** [Makefile:43: html] Error 2
```
Am I the only one getting this error, or is this reproducible on another machine?

**Comment by pllim** [comment]
I don't think there is anything we can do on our side for that error. The server was either down or temporarily blacklisted your IP for too many hits.

**Comment by kakirastern** [comment]
I think I am getting the same error on GitHub too, so their server might be down indeed.
