### ISSUE TITLE
Check existing tutorial tests against Astropy Version 4.0

### ISSUE THREAD

**Issue by eblur** [astropy/astropy-tutorials#428]
It's possible that the update to Astropy 4.0 has broken some of our past tutorial notebooks. Some one needs to check and update any old notebooks.

http://docs.astropy.org/en/stable/whatsnew/4.0.html

**Comment by kakirastern** [comment]
One issue just came up is from the `vo` tutorial: 

```
INFO: Processing notebook conesearch.ipynb (in /home/circleci/project/tutorials/notebooks/vo) [convert]

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/circleci/project/venv/lib/python3.7/site-packages/sphinx/config.py", line 348, in eval_config_file
    execfile_(filename, namespace)
  File "/home/circleci/project/venv/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/home/circleci/project/tutorials/conf.py", line 164, in <module>
    process_notebooks(nb_tutorials_path, **processkwargs)
  File "/home/circleci/project/scripts/convert.py", line 238, in process_notebooks
    nbc.execute()
  File "/home/circleci/project/scripts/convert.py", line 97, in execute
    executor.preprocess(nb, {'metadata': {'path': self.path_only}})
  File "/home/circleci/project/venv/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/home/circleci/project/venv/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/home/circleci/project/venv/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
print('First non-empty table returned by', result.url)
print('Number of rows is', result.nrows)
------------------


AttributeErrorTraceback (most recent call last)
<ipython-input-6-f606a14c3024> in <module>
      1 print('First non-empty table returned by', result.url)
----> 2 print('Number of rows is', result.nrows)

AttributeError: 'Table' object has no attribute 'nrows'
AttributeError: 'Table' object has no attribute 'nrows'


make: *** [Makefile:43: html] Error 2

Exited with code exit status 2
```

**Comment by pllim** [comment]
Re: vo -- My bad. See #427

**Comment by kakirastern** [comment]
@pllim No worries, just updated the code to make things work again.

**Comment by pllim** [comment]
I think this can be closed now?

**Comment by bsipocz** [comment]
It would be great to make this a standing exercise, preferably before a new release is going out (either test against the dev version, or during the release candidate testing period).
