### ISSUE TITLE
Error "... object has no attribute 'to_value'" in distances.py

### ISSUE THREAD

**Issue by rr34** [astropy/astropy-tutorials#512]
### Description

Error during the [Astronomical Coordinates Astropy tutorial](https://www.astropy.org/astropy-tutorials/rst-tutorials/1-Coordinates-Intro.html?highlight=filtertutorials) on step 27 where it converts from parallax to parsecs. Error "... object has no attribute 'to_value'" in distances.py on line 148.

### Expected behavior

I copy-pasted the code from the tutorial so I expected no errors. Looks like an update that didn't get implemented in that one particular instance in distances.py

### Actual behavior
Error, but I think I fixed it on my own system. I found [the appropriate wording for equivalency conversions here](https://docs.astropy.org/en/stable/units/equivalencies.html). I made the change in my local library and successfully completed the tutorial. I suggested the change [with a fork on GitHub here](https://github.com/rr34/astropy/commit/a0930afe565ab3ced762db10fe2c0929b3f8fe72).

### Steps to Reproduce

1. [Astropy tutorial here](https://www.astropy.org/astropy-tutorials/rst-tutorials/1-Coordinates-Intro.html?highlight=filtertutorials).
2. See step 27.
```python
# Put your Python code snippet here.
```

### System Details

The error and correction occurred the same both on my Windows computer running PyCharm below and Raspberry Pi Zero W.

"C:\Users\nate\PycharmProjects\pythonProject\HelloWorld\Raspberry Pi Zero W\Scripts\python.exe" C:/Users/nate/PycharmProjects/pythonProject/HelloWorld/systemdetails.py
Windows-10-10.0.19042-SP0
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
Numpy 1.21.5
pyerfa 2.0.0.1
astropy 5.0
Scipy 1.7.3
Matplotlib 3.5.1

**Comment by pllim** [comment]
FYI -- I tranferred this to tutorial repo, in case this is something that can be fixed on the tutorial side. cc @adrn

**Comment by eerovaher** [comment]
What is the full error message?

**Comment by rr34** [comment]
Traceback (most recent call last):
  File "C:\Users\nate\PycharmProjects\pythonProject\HelloWorld\main.py", line 80, in <module>
    gaia_dist = Distance(parallax=ngc188_table_3d['parallax'])
  File "C:\Users\nate\PycharmProjects\pythonProject\HelloWorld\Raspberry Pi Zero W\lib\site-packages\astropy\coordinates\distances.py", line 149, in __new__
    value = parallax.to_value(u.pc, equivalencies=u.parallax())
AttributeError: 'MaskedColumn' object has no attribute 'to_value'

Sorry. There is the full error.

Nathan Ruffing
+1-614-205-1285
https://nathanruffing.com/


----- Original message -----

**Comment by rr34** [comment]
Here is my entire code just so you can see what line 80 is in my code. Kind of a mess I'm just experimenting with it you can see I just called it HelloWorld.


-----Code starts next line-----
# This is a sample Python script.
# Press Shift+F10 to execute it or replace it with your code.
# Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.


def print_hi(name):
    # Use a breakpoint in the code line below to debug your script.
    print(f'Hi, {name}')  # Press Ctrl+F8 to toggle the breakpoint.


# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    print_hi('PyCharm')

import matplotlib.pyplot as plt
# %matplotlib inline
import numpy as np

from astropy import units as u
from astropy.coordinates import SkyCoord, Distance
from astropy.io import fits
from astropy.table import QTable
from astropy.utils.data import download_file

from astroquery.gaia import Gaia
Gaia.ROW_LIMIT = 10000  # Set the row limit for returned data

#2
# ngc188_center = SkyCoord(12.11*u.deg, 85.26*u.deg)
# ngc188_center

#3
# ngc188_center = SkyCoord(12.11*u.deg, 85.26*u.deg, frame='icrs')
# ngc188_center

#6
ngc188_center = SkyCoord.from_name('NGC 188', frame='icrs')
ngc188_center

job = Gaia.cone_search_async(ngc188_center, radius=0.5*u.deg)
ngc188_table = job.get_results()

# only keep stars brighter than G=19 magnitude
ngc188_table = ngc188_table[ngc188_table['phot_g_mean_mag'] < 19*u.mag]

#15
cols = ['source_id',
 'ra',
 'dec',
 'parallax',
 'parallax_error',
 'pmra',
 'pmdec',
 'radial_velocity',
 'phot_g_mean_mag',
 'phot_bp_mean_mag',
 'phot_rp_mean_mag']

#16
ngc188_table[cols].write('gaia_results.fits', overwrite=True)

#17
print(len(ngc188_table))

#20
ngc188_gaia_coords = SkyCoord(ngc188_table['ra'], ngc188_table['dec'])

#24
ngc188_center_3d = SkyCoord(12.11*u.deg, 85.26*u.deg, distance=1.96*u.kpc)

#25
parallax_snr = ngc188_table['parallax'] / ngc188_table['parallax_error']
ngc188_table_3d = ngc188_table[parallax_snr > 10]
print(len(ngc188_table_3d))

#26
# Distance(parallax=1*u.mas)

#27
gaia_dist = Distance(parallax=ngc188_table_3d['parallax'])

#28
ngc188_coords_3d = SkyCoord(ra=ngc188_table_3d['ra'],
                            dec=ngc188_table_3d['dec'],
                            distance=gaia_dist)

#29
fig, ax = plt.subplots(figsize=(6.5, 5.2),
                       constrained_layout=True)
cs = ax.scatter(ngc188_coords_3d.ra.degree,
                ngc188_coords_3d.dec.degree,
                c=ngc188_coords_3d.distance.kpc,
                s=5, vmin=1.5, vmax=2.5, cmap='twilight')
cb = fig.colorbar(cs)
cb.set_label(f'distance [{u.kpc:latex_inline}]')

ax.set_xlabel('RA [deg]')
ax.set_ylabel('Dec [deg]')

ax.set_title('Gaia DR2 sources near NGC 188', fontsize=18)

# display on Raspberry Pi?

plt.savefig('cool_plot-2.png')

from kivy.app import App
from kivy.uix.gridlayout import GridLayout
from kivy.uix.label import Label
from kivy.uix.image import Image
from kivy.uix.button import Button
from kivy.uix.textinput import TextInput

class DisplayPlot(App):
    def build(self):
        self.window = GridLayout()
        self.window.cols = 1

        self.window.add_widget(Image(source="cool_plot-2.png"))

        return self.window

DisplayPlot().run()

**Comment by eerovaher** [comment]
The fact that the error mentions `MaskedColumn` indicates that your data is in a `Table`, not a `QTable`, and that is the reason why creating `Distance` objects fails.

The tutorial writes the Gaia archive query result to a file and then reads it in as a `QTable`:
```python
In[16]:
ngc188_table = QTable.read('gaia_results.fits')
```
This ensures that the relevant columns get converted to `Quantity` (or `MaskedQuantity`) instances, as explained a few paragraphs below (beginning with "Note that, because the Gaia archive..."). It should be pointed out that writing and reading the data is not required to perform the conversion, it would be enough to do:
```python
ngc188_table = QTable(ngc188_table)
```

That being said it might be better if `astroquery` output would already be a `QTable` instead of a `Table`, and it might also be a good idea to update the `Distance` constructor if it becomes less picky about the type of its inputs as a result.

**Comment by adrn** [comment]
I think the tutorial link you found is a slightly out of date version of the tutorial, so thanks for finding and reporting this, I'll have to track down how to get rid of those pages or at least put a warning up! The newer version of the tutorial is here, which I believe handles the masking issue: https://learn.astropy.org/tutorials/1-Coordinates-Intro.html

**Comment by jeffjennings** [comment]
[This issue has been identified as one that is no longer current. In an effort to clean up past issues, it will be closed. See below for confirmation that the issue has been resolved. If you have further questions, please open a new issue. Thank you.]

The tutorial has been updated since the time of this issue and is confirmed to be running without error.
